# Stage 03 — Python Fundamentals Practice Notebook

This starter notebook is designed for the **Python Fundamentals** project stage.

### Goals
By the end, you should have practiced:
- Core Python
- NumPy
- pandas
- Working with dummy data
- Writing reusable utility functions
- Importing functions from `src/utils.py`

> **How to use this notebook:** Complete each `TODO` cell yourself. Try not to look up the answer immediately.

## 0. Setup

### TODO
1. Import `numpy` as `np`.
2. Import `pandas` as `pd`.
3. Print the installed versions of NumPy and pandas.

In [2]:
# TODO: Import NumPy and pandas
import numpy as np
import pandas as pd

# TODO: Print their versions
print("NumPy version:", np.__version__)
print("pandas version:", pd.__version__)

NumPy version: 2.2.6
pandas version: 2.3.3

## 1. Python Basics — Variables and Data Types

Create variables representing a mock transaction:
- `transaction_id` — an integer
- `customer_name` — a string
- `amount` — a float
- `is_fraud` — a boolean

Then print each variable and its type.

In [4]:
# TODO: Create the four variables
transaction_id = 123456
customer_name = "Harvey Specter"
amount = 250.75
is_fraud = True

# TODO: Print each variable and its type
print("Transaction ID: ", transaction_id, "Type: ", type(transaction_id))
print("Customer Name: ", customer_name, "Type: ", type(customer_name))
print("Amount: ", amount, "Type: ", type(amount))
print("Is Fraud: ", is_fraud, "Type: ", type(is_fraud))

Transaction ID:  123456 Type:  <class 'int'>
Customer Name:  Harvey Specter Type:  <class 'str'>
Amount:  250.75 Type:  <class 'float'>
Is Fraud:  True Type:  <class 'bool'>

## 2. Python Collections

Create a list called `amounts` containing at least 6 transaction amounts.

### TODO
- Print the first amount.
- Print the last amount.
- Print the first three amounts.
- Find the number of elements using `len()`.
- Compute the total using `sum()`.
- Compute the average using basic Python only.

In [5]:
# TODO: Create a list of transaction amounts
amounts = [100.50, 200.75, 150.00, 300.25, 250.75]

# TODO: Practice indexing and slicing
print("First amount: ", amounts[0])
print("Last amount: ", amounts[-1])

for i in range(3):
    print("Amount of the transaction at index ", i, "is: ", amounts[i])

# TODO: Calculate length, total, and average
print("The number of elements in the list is: ", len(amounts))
total = sum(amounts)
print("Total of all amounts: ", total)
print("Average of all amounts: ", total/len(amounts))

First amount:  100.5
Last amount:  250.75
Amount of the transaction at index  0 is:  100.5
Amount of the transaction at index  1 is:  200.75
Amount of the transaction at index  2 is:  150.0
The number of elements in the list is:  5
Total of all amounts:  1002.25
Average of all amounts:  200.45

## 3. Conditionals

Using one transaction amount, classify it as:

- `"small"` if amount < 100
- `"medium"` if 100 <= amount < 1000
- `"large"` if amount >= 1000

In [6]:
amount = 750

# TODO: Write an if / elif / else statement
if amount < 100:
    print("small")
elif amount < 1000:
    print("medium")
else:
    print("large")

medium

## 4. Loops

Use the `amounts` list from earlier.

### TODO
Loop through the amounts and print:

`Transaction amount: <amount>`

Then create a new list containing only amounts greater than 500.

In [8]:
# TODO: Write a for loop
for amount in amounts:
    print("Amount: ", amount)

# TODO: Create a list containing amounts > 500
large_amounts = []
for amount in amounts:
    if amount > 500:
        large_amounts.append(amount)
large_amounts

Amount:  100.5
Amount:  200.75
Amount:  150.0
Amount:  300.25
Amount:  250.75

[]

## 5. Write a Simple Python Function

Create a function:

```python
def classify_transaction(amount):
    ...
```

It should return `"small"`, `"medium"`, or `"large"` using the rules from the earlier exercise.

Test it with at least three values.

In [9]:
# TODO: Define classify_transaction(amount)
def classify_transaction(amount):
    if amount < 100:
        return "small"
    elif amount < 1000:
        return "medium"
    else:
        return "large"

# TODO: Test your function
for amount in amounts:
    classification = classify_transaction(amount)
    print(classification)

medium
medium
medium
medium
medium

# NumPy Practice

## 6. Create a NumPy Array

Create a NumPy array called `transaction_amounts` with at least 8 numeric values.

### TODO
Print:
- The array
- Its type
- Its shape
- Its number of dimensions
- Its data type

In [10]:
# TODO: Create transaction_amounts
transaction_amounts = np.array([100.50, 200.75, 150.00, 300.25, 250.75, 900.80, 1200.00, 50.25, 75.00, 600.50])
# TODO: Inspect the array
print("Transaction Amounts: ", transaction_amounts)
print("Type: ", type(transaction_amounts))
print("Shape: ", transaction_amounts.shape)
print("Number of dimensions: ", transaction_amounts.ndim)
print("Data type: ", transaction_amounts.dtype)

Transaction Amounts:  [ 100.5   200.75  150.    300.25  250.75  900.8  1200.     50.25   75.
  600.5 ]
Type:  <class 'numpy.ndarray'>
Shape:  (10,)
Number of dimensions:  1
Data type:  float64

## 7. NumPy Summary Statistics

Using `transaction_amounts`, calculate:

- Mean
- Median
- Minimum
- Maximum
- Standard deviation
- Sum

In [12]:
# TODO: Calculate NumPy summary statistics
print("mean: ", np.mean(transaction_amounts))
print("median: ", np.median(transaction_amounts))
print("std: ", np.std(transaction_amounts))
print("min: ", np.min(transaction_amounts))
print("max: ", np.max(transaction_amounts))
print("sum: ", np.sum(transaction_amounts))

mean:  382.88
median:  225.75
std:  371.5032228662358
min:  50.25
max:  1200.0
sum:  3828.8

## 8. NumPy Boolean Masks

### TODO
Create a Boolean mask identifying transactions greater than 500.

Then use the mask to return only those transactions.

Try printing both:
1. The Boolean mask
2. The filtered values

In [13]:
# TODO: Create a Boolean mask
mask = transaction_amounts > 500
# TODO: Use it to filter transaction_amounts
filtered_amounts = transaction_amounts[mask]
filtered_amounts

array([ 900.8, 1200. ,  600.5])

## 9. Random Data with NumPy

Use:

```python
np.random.seed(42)
```

Then generate 10 random transaction amounts between 10 and 2000.

### TODO
- Store them in `random_amounts`.
- Print the result.
- Find how many are greater than 1000.

In [15]:
np.random.seed(42)

# TODO: Generate 10 random amounts
arr = np.random.randint(1,2000,size=10)
print(arr)

# TODO: Count values > 1000
count = 0
for amount in arr:
    if amount > 1000:
        count+=1
print(count)

[1127 1460  861 1295 1131 1096 1725 1045 1639  122]
8

# pandas Practice

## 10. Create a Dummy DataFrame

Create a DataFrame named `df` with these columns:

- `transaction_id`
- `customer`
- `amount`
- `category`
- `is_fraud`

Use at least 8 rows of dummy data.

In [16]:
# TODO: Create a dictionary containing dummy transaction data
data = {
    "transaction_id": [1, 2, 3, 4, 5, 6, 7, 8],
    "customer": ["Alice", "Bob", "Charlie", "David", "Emma", "Frank", "Grace", "Henry"],
    "amount": [120, 550, 75, 1300, 420, 900, 50, 2100],
    "category": ["Food", "Shopping", "Food", "Travel", "Shopping", "Travel", "Food", "Shopping"],
    "is_fraud": [False, False, False, True, False, False, False, True]
}
# TODO: Convert it into a pandas DataFrame named df
df = pd.DataFrame(data)

# TODO: Display df
df

   transaction_id customer  amount  category  is_fraud
0               1    Alice     120      Food     False
1               2      Bob     550  Shopping     False
2               3  Charlie      75      Food     False
3               4    David    1300    Travel      True
4               5     Emma     420  Shopping     False
5               6    Frank     900    Travel     False
6               7    Grace      50      Food     False
7               8    Henry    2100  Shopping      True

## 11. Inspect the DataFrame

Use pandas to inspect the dataset.

### TODO
Try:
- `df.head()`
- `df.tail()`
- `df.shape`
- `df.columns`
- `df.dtypes`
- `df.info()`
- `df.describe()`

Run them separately if you want to see each output clearly.

In [19]:
# TODO: Inspect df
print(df.head())
print(df.info())

   transaction_id customer  amount  category  is_fraud
0               1    Alice     120      Food     False
1               2      Bob     550  Shopping     False
2               3  Charlie      75      Food     False
3               4    David    1300    Travel      True
4               5     Emma     420  Shopping     False
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  8 non-null      int64
 1   customer        8 non-null      object
 2   amount          8 non-null      int64
 3   category        8 non-null      object
 4   is_fraud        8 non-null      bool
dtypes: bool(1), int64(2), object(2)
memory usage: 392.0+ bytes
None

## 12. Select Rows and Columns

### TODO
Practice each of these:

1. Select only the `amount` column.
2. Select `customer` and `amount`.
3. Select the first row using `.iloc`.
4. Select the first three rows.
5. Filter transactions where `amount > 500`.
6. Filter transactions where `is_fraud == True`.

In [20]:
# TODO: Column selection
df['amount']
df[['customer', 'amount']]
# TODO: iloc
df.iloc[0]  # First row
df.iloc[0:3]  # First three rows

# TODO: Filtering
df[df['amount'] > 1000]
df[df['is_fraud'] == True]

   transaction_id customer  amount  category  is_fraud
3               4    David    1300    Travel      True
7               8    Henry    2100  Shopping      True

## 13. Create New Columns

### TODO

Create:
1. `fee` = 2% of `amount`
2. `net_amount` = `amount - fee`
3. `large_transaction` = `True` when amount >= 1000, otherwise `False`

In [21]:
# TODO: Create fee
df['fee'] = df['amount'] * 0.02

# TODO: Create net_amount
df['net_amount'] = df['amount'] - df['fee']

# TODO: Create large_transaction
df['large_transaction'] = df['amount'] > 1000

# Display the updated DataFrame
df

,transaction_id,customer,amount,category,is_fraud,fee,net_amount,large_transaction
0,1,Alice,120,Food,False,2.4,117.6,False
1,2,Bob,550,Shopping,False,11.0,539.0,False
2,3,Charlie,75,Food,False,1.5,73.5,False
3,4,David,1300,Travel,True,26.0,1274.0,True
4,5,Emma,420,Shopping,False,8.4,411.6,False
5,6,Frank,900,Travel,False,18.0,882.0,False
6,7,Grace,50,Food,False,1.0,49.0,False
7,8,Henry,2100,Shopping,True,42.0,2058.0,True

## 14. Missing Values

Introduce a few missing values into a copy of your DataFrame.

### TODO
1. Make a copy called `df_missing`.
2. Set at least two values to `np.nan`.
3. Use `isna()` and `isna().sum()` to inspect missingness.
4. Try `dropna()`.
5. Try `fillna()` with a reasonable replacement.

In [23]:
# TODO: Make a copy
df_missing = df.copy()

# TODO: Introduce missing values
df_missing.loc[2, 'amount'] = np.nan
df_missing.loc[5, 'customer'] = np.nan

# TODO: Inspect missing values
df_missing.isna().sum()

transaction_id       0
customer             1
amount               1
category             0
is_fraud             0
fee                  0
net_amount           0
large_transaction    0
dtype: int64

In [24]:
# TODO: Try dropna()
df_missing.dropna()

,transaction_id,customer,amount,category,is_fraud,fee,net_amount,large_transaction
0,1,Alice,120.0,Food,False,2.4,117.6,False
1,2,Bob,550.0,Shopping,False,11.0,539.0,False
3,4,David,1300.0,Travel,True,26.0,1274.0,True
4,5,Emma,420.0,Shopping,False,8.4,411.6,False
6,7,Grace,50.0,Food,False,1.0,49.0,False
7,8,Henry,2100.0,Shopping,True,42.0,2058.0,True

In [25]:
# TODO: Try fillna()
df_missing.fillna({'amount': df_missing['amount'].mean(), 'customer': 'Unknown'})

,transaction_id,customer,amount,category,is_fraud,fee,net_amount,large_transaction
0,1,Alice,120.000000,Food,False,2.4,117.6,False
1,2,Bob,550.000000,Shopping,False,11.0,539.0,False
2,3,Charlie,777.142857,Food,False,1.5,73.5,False
3,4,David,1300.000000,Travel,True,26.0,1274.0,True
4,5,Emma,420.000000,Shopping,False,8.4,411.6,False
5,6,Unknown,900.000000,Travel,False,18.0,882.0,False
6,7,Grace,50.000000,Food,False,1.0,49.0,False
7,8,Henry,2100.000000,Shopping,True,42.0,2058.0,True

## 15. GroupBy

Use `groupby()` to answer:

1. What is the average transaction amount by category?
2. What is the total transaction amount by category?
3. How many transactions are in each category?

In [ ]:
# TODO: Average amount by category


# TODO: Total amount by category


# TODO: Transaction count by category

## 16. Sorting

### TODO
Sort the DataFrame:
1. By `amount`, from smallest to largest.
2. By `amount`, from largest to smallest.

In [ ]:
# TODO: Sort ascending


# TODO: Sort descending

## 17. String Cleaning

Modify some customer names so they contain inconsistent capitalization or extra spaces.

Examples:

```text
" alice "
"BOB"
"cHaRlIe"
```

### TODO
Use pandas string methods such as:
- `.str.strip()`
- `.str.lower()`
- `.str.title()`

Create a cleaned customer-name column.

In [ ]:
# TODO: Introduce messy customer names


# TODO: Clean them

# Reusable Utility Functions

## 18. Utility Function — Summary Statistics

Write a reusable function called:

```python
get_summary_stats(df)
```

It should:
1. Select numeric columns.
2. Return useful summary statistics for those columns.

You may start with `df.describe()`, or build something more customized.

In [26]:
# TODO: Write get_summary_stats(df)
def get_summary_stats(df):
    summary = {
        'mean': df['amount'].mean(),
        'median': df['amount'].median(),
        'std': df['amount'].std(),
        'min': df['amount'].min(),
        'max': df['amount'].max(),
        'sum': df['amount'].sum()
    }
    return summary


# TODO: Test it on df
get_summary_stats(df)

{'mean': np.float64(689.375),
 'median': np.float64(485.0),
 'std': np.float64(718.0849407576078),
 'min': np.int64(50),
 'max': np.int64(2100),
 'sum': np.int64(5515)}

## 19. Utility Function — Column Name Cleaner

Write a function:

```python
clean_column_names(df)
```

It should return a copy of the DataFrame where column names:
- are lowercase
- have leading/trailing spaces removed
- replace spaces with underscores

Example:

```text
"Transaction ID " -> "transaction_id"
```

In [28]:
# TODO: Write clean_column_names(df)
def clean_column_names(df):
    df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '')
    return df


# TODO: Test it with a small example DataFrame
test_df = pd.DataFrame({
    ' Column 1 ': [1, 2, 3],
    ' Column 2 ': [4, 5, 6]
})
print("Before cleaning:")
print(test_df)
clean_column_names(test_df)

Before cleaning:
   Column 1   Column 2
0          1          4
1          2          5
2          3          6

   column_1  column_2
0         1         4
1         2         5
2         3         6

## 20. Save a Function to `src/utils.py`

Your assignment requires at least one reusable function in:

```text
project/
└── src/
    └── utils.py
```

### TODO
Choose one of your functions above and manually place it in `src/utils.py`.

A good `utils.py` might eventually contain:

```python
def get_summary_stats(df):
    ...

def clean_column_names(df):
    ...
```

Do **not** duplicate lots of notebook-specific code in `utils.py`; keep reusable functions there.

## 21. Import Your Utility Function

After saving your function in `src/utils.py`, try importing it.

If this notebook is inside `project/notebooks/`, you may need to add the project root to Python's import path.

### TODO
Complete the code below.

In [ ]:
from pathlib import Path
import sys

# TODO:
# Find the project root.
# Hint: if the notebook is in project/notebooks/,
# the parent of the notebooks folder is the project root.

PROJECT_ROOT = ...

# TODO: Add PROJECT_ROOT to sys.path if necessary


# TODO: Import your function
# from src.utils import get_summary_stats


# TODO: Test the imported function

# Mini Challenge

## 22. Transaction Analysis Challenge

Using your dummy DataFrame, answer all of these:

1. How many transactions are there?
2. What is the mean transaction amount?
3. What is the largest transaction?
4. Which customer made the largest transaction?
5. How many transactions are above \$500?
6. What percentage of transactions are marked as fraud?
7. Which category has the highest average transaction amount?

Try to solve each question with pandas rather than manually reading the table.

In [ ]:
# TODO 1: Number of transactions


# TODO 2: Mean amount


# TODO 3: Largest transaction


# TODO 4: Customer with largest transaction


# TODO 5: Count amount > 500


# TODO 6: Fraud percentage


# TODO 7: Category with highest average amount

# Optional Practice

## 23. Optional — Add a Basic Test

If you choose the **tests folder** option from the assignment, your structure could look like:

```text
project/
├── notebooks/
│   └── python_fundamentals_summary.ipynb
├── src/
│   └── utils.py
└── tests/
    └── test_utils.py
```

For example, if you create `clean_column_names()`, think about:

- What input should you test?
- What output do you expect?
- What would indicate that the function is broken?

### TODO
Write down one test case in plain English below.

In [ ]:
# TODO: Write a simple assert-based test here first.
# Later, you can move it into tests/test_utils.py.

## 24. Reflection

Write a few sentences answering:

1. Which Python concept felt most natural?
2. Which NumPy operation was new to you?
3. Which pandas operation do you think will be most useful later?
4. What reusable function did you choose for `src/utils.py`?
5. How might you reuse it during data preprocessing or EDA?

**TODO: Write your reflection here.**

- Python:
- NumPy:
- pandas:
- Utility function:
- Future use:

# Completion Checklist

Before submitting this stage, make sure you have:

- [ ] Practiced basic Python
- [ ] Used NumPy arrays and Boolean masks
- [ ] Created and manipulated a pandas DataFrame
- [ ] Practiced filtering, grouping, sorting, and missing values
- [ ] Written at least one reusable function
- [ ] Saved a reusable function in `src/utils.py`
- [ ] Imported that function back into this notebook
- [ ] Added documentation, a second function, or a basic test
- [ ] Saved this notebook as `notebooks/python_fundamentals_summary.ipynb`
- [ ] Committed and pushed your changes to GitHub